### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by tispratik** [zamith/sass_elixir#1]
Hello, can you please provide some docs on how this can be used? I stumbled upon this link from awesome_elixir github page.

**Comment by zamith** [comment]
@tispratik This was an experiment that I didn't really kept on with, sorry about that. I believe you would be better served by looking at stuff by @HashNuke, he should be able to help you better than I would.

However, if you're looking at using Sass with Phoenix, see [this answer](http://stackoverflow.com/questions/31978664/how-to-use-sass-scss-with-phoenix-framework). Hope it helps.
